/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlobId' : ExternalBlob,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'videoId' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'hashtags' : IDL.Vec(IDL.Text),
  'thumbnailBlobId' : ExternalBlob,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'timestamp' : Time,
  'blobId' : ExternalBlob,
  'uploader' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForVideo' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTrendingHashtags' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoById' : IDL.Func([IDL.Nat], [Video], ['query']),
  'getVideosByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'getVideosPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Video)],
      ['query'],
    ),
  'incrementViews' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'likeVideo' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob, ExternalBlob],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlobId' : ExternalBlob,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'videoId' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'hashtags' : IDL.Vec(IDL.Text),
    'thumbnailBlobId' : ExternalBlob,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'timestamp' : Time,
    'blobId' : ExternalBlob,
    'uploader' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForVideo' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTrendingHashtags' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoById' : IDL.Func([IDL.Nat], [Video], ['query']),
    'getVideosByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'getVideosPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'incrementViews' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [], []),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'likeVideo' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob, ExternalBlob],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };